Feature/add support for metadata filtering
Aleph-Alpha/intelligence-layer-sdk pull request #969
Opened 2024-08-01 16:31 UTC by avaxaleph

# Description
The DocumentIndex API now supports metadata filtering through the new `filter-index` feature. Based on this, the `DocumentIndex` client in the Intelligence-Layer was updated with the following:
- ability to create a filter-index in a namespace
- ability to assign/unassign a filter-index to/from an existing search index
- ability to list assigned filter-indexes for a search index
- ability to search in a collection with metadata filtering by following the allowed criteria and data types allowed by the DI API

Additionally, I've updated the tutorial notebook for the `DocumentIndex` to reflect how to use this functionality.

## Before Merging
 - [ ] Review the code changes
    - Unused print / comments / TODOs
    - Missing docstrings for functions that should have them
    - Consistent variable names
    - ...
 - [ ] Update `changelog.md` if necessary
 - [ ] Commit messages should contain a semantic [label](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) and the ticket number
   - Consider squashing if this is not the case

2024-08-02 12:52 UTC, SebastianNiehusAA commented
Thank you for the PR. Really cool feature. I don't see any issues with the code and it's also very useful that you added the section to the notebook (I just fixed some typos and formatting issues there).
@filippoberga there are two things we should discuss before merging:
 - Adding tests for the filtering methods
 - Adding a small how-to notebook

2024-08-02 12:54 UTC, SebastianNiehusAA requested changes
TODO for IL Team
 - Tests
 - How-to notebook
 - Add CHANGELOG entry

2024-08-02 13:05 UTC, avaxaleph commented
> Thank you for the PR. Really cool feature. I don't see any issues with the code and it's also very useful that you added the section to the notebook (I just fixed some typos and formatting issues there). @filippoberga there are two things we should discuss before merging:
> 
> * Adding tests for the filtering methods
> * Adding a small how-to notebook

Thanks @SebastianNiehusAA  ! I've also wanted to add the tests but I saw that a certain DI collection is used there and I don't have access to it.

2024-08-02 13:13 UTC, SebastianNiehusAA commented
> > Thank you for the PR. Really cool feature. I don't see any issues with the code and it's also very useful that you added the section to the notebook (I just fixed some typos and formatting issues there). @filippoberga there are two things we should discuss before merging:
> > 
> > * Adding tests for the filtering methods
> > * Adding a small how-to notebook
> 
> Thanks @SebastianNiehusAA ! I've also wanted to add the tests but I saw that a certain DI collection is used there and I don't have access to it. The token is injected during the CI build, right?

We inject the necessary tokens during CI, yes. For me it is also working locally. Normally you only need the "usual" tokens as for the other tests in IL, e.g. the AA_TOKEN. Have you set up your tokens as outlined in env.sample?

2024-08-09 20:34 UTC, avaxaleph commented
@SebastianNiehusAA @filippoberga I've added the test. You can review the PR again.

2024-08-12 08:08 UTC, SebastianNiehusAA requested changes
Tests are looking good. I only found an issue with the index name that needs fixing

2024-08-12 08:08 UTC, SebastianNiehusAA commented on src/documentation/document_index.ipynb
> +    "    index_name=\"asym-128\",  # we assign it to asym-128\n",
If we are using `intelligence-layer-sdk-demo-collection` as a collection as assigned in the third cell, there does not seem to be an `asym-128` index. We could use `intelligence-layer-sdk-demo-index` instead.

2024-08-12 08:08 UTC, SebastianNiehusAA commented on src/documentation/document_index.ipynb
> +    "    collection_path=collection_path, index_name=\"asym-128\"\n",
see comment above (asym-128 does not exists in the current collection)

2024-08-12 08:08 UTC, SebastianNiehusAA commented on src/documentation/document_index.ipynb
> +    "    index_name=\"asym-128\",\n",
see comment above (asym-128 does not exists in the current collection)

2024-08-13 12:54 UTC, merged